name: Deploy Frontend DEV

on:
  push:
    branches: [dev]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npm run build
        env:
          VITE_API_URL: https://dev.eifavpn.ru
          VITE_TELEGRAM_BOT_USERNAME: EIFA_VPNbot

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 5.101.81.90
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/"
          target: /opt/eifavpn/dev/frontend/
          overwrite: true
          strip_components: 0
